### run the file after populating the db

GET localhost:8080/api/v1/addresses/2

###

PUT localhost:8080/api/v1/addresses/2
content-type: application/json

{
  "latitude": 30,
  "longitude": 29,
  "countryCode": "TUR",
  "city": "Angara",
  "region": "Mutlu Semt",
  "addressLine": "Arkacı Mahallesi",
  "addressDetails": "1/67",
  "contactPhone": "+90 777 888 99 99"
}

###

GET localhost:8080/api/v1/addresses/

###

DELETE localhost:8080/api/v1/addresses/3

###

GET localhost:8080/api/v1/addresses/3/coordinates

###

GET localhost:8080/api/v1/addresses/2/coordinates

###