services:
  ddd-main-database:
    image: postgres:16.2
    container_name: ddd_main_db
    environment:
      POSTGRES_DB: dddmaindb
      POSTGRES_USER: dingdong
      POSTGRES_PASSWORD: delicious
    ports:
      - "5432:5432"
    restart: always

  ddd-main-service:
    build: .
    container_name: ddd_main_service
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ddd-main-database:5432/dddmaindb
        - SPRING_DATASOURCE_USERNAME=dingdong
        - SPRING_DATASOURCE_PASSWORD=delicious
        - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_JPA_SHOW_SQL=true
        - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

    depends_on:
      - ddd-main-database
    restart: always